CREATE TABLE AGV_ERR_NAME(
	
	ERR_CODE INT NOT NULL  DEFAULT 0,
	ERR_NAME NVARCHAR(45) NOT NULL DEFAULT '',
	ERR_DETAIL NVARCHAR(200) NOT NULL DEFAULT '',
	ERR_RECOVERY NVARCHAR(200) NOT NULL DEFAULT '',
	MAKE_TIME DATETIME NOT NULL DEFAULT GETDATE(),
	
	CONSTRAINT AGV_ERR_NAME_PK PRIMARY KEY(ERR_CODE))