CREATE TABLE AUTORATOR_STATE(

	AUTORATOR_ID INT IDENTITY(1,1) NOT NULL,
	COMMAND_TIME DATETIME NOT NULL DEFAULT '',
	TOTAL_STATE INT NOT NULL DEFAULT 0,
	ERR_CODE INT NOT NULL DEFAULT 0,
	FLOOR INT NOT NULL DEFAULT 0,
	IN_FLOOR INT NOT NULL DEFAULT 0,
	IN_STATE INT NOT NULL DEFAULT 0,
	OUT_FLOOR INT NOT NULL DEFAULT 0,
	OUT_STATE INT NOT NULL DEFAULT 0,
	MAKE_TIME DATETIME NOT NULL DEFAULT GETDATE(),
	LAST_TIME DATETIME NOT NULL DEFAULT GETDATE(),

	CONSTRAINT AUTORATOR_STATE_PK PRIMARY KEY(AUTORATOR_ID))